### ISSUE TITLE
"jsonb" does not exist

### ISSUE THREAD

**Issue by bardolf69** [greys-bots/form-fox#10]
I'm just trying to setup my own copy of the form fox bot but when I run node bot/bot I get and error "jsonb" does not exist.  It does say fox ready after the error but the bot doesn't respond to commands.  Here is a screenshot of the error.
![Screenshot 2021-10-15 074014](https://user-images.githubusercontent.com/47841636/137414364-6a2c3c51-db69-4de3-96f7-f989c639f30b.png)

**Comment by selenated** [comment]
What version of postgres do you have installed?

**Comment by bardolf69** [comment]
9.2.24 running with CPanel so not sure if they remove something.  I normally use MySQL so I'm not overly familiar with Postgres.

**Comment by selenated** [comment]
Ahh, that'd be the issue I think... Looks like you need at least 9.6, we typically use version 12 at the very least. If you can update postgres then you should be good

**Comment by bardolf69** [comment]
ok so after half a day of messing around because CPanel doesn't like anything over 9.2 I now have postgres 12 installed and all is working well.  Thanks for the support :)
