### ISSUE TITLE
[Feature] Website

### ISSUE THREAD

**Issue by greysdawn** [greys-bots/form-fox#18]
(Moving from old project cards to issues)

This won't happen for a while, but we plan to have a website for the bot eventually. Part of those plans involve having bot docs, a dashboard for server/form management, and potentially a place to share form templates as well

I'll try to keep this issue updated with things as we go along

### Basic functionality
- [ ] landing page
- [ ] documentation

### Dashboard
- [ ] server list with option to invite to servers
- [ ] form management
  - [ ] CRUD
  - [ ] question management
- [ ] response management
- [ ] API and docs for use

### Bonus
- [ ] Area to share form templates (verification, tournament, giveaway, etc)

**Comment by greysdawn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Website](https://trello.com/c/stPFLAjO/9-website)

**Comment by selenated** [comment]
Closing for now as we have other plans for the dashboard/website!
