### ISSUE TITLE
Auto-DM users a form upon join

### ISSUE THREAD

**Issue by selenated** [greys-bots/form-fox#22]
Set up a config option for a form ID to send to users when they join a server

**Comment by selenated** [comment]
Added in a9f6771; currently waiting on intent whitelisting

**Comment by greysdawn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Auto-DM upon join](https://trello.com/c/G4GTyo4m/10-auto-dm-upon-join)

**Comment by selenated** [comment]
Intent whitelisted, feature is now functional!
