### ISSUE TITLE
Auto-thread when response is posted !

### ISSUE THREAD

**Issue by Allread** [greys-bots/form-fox#24]
Hello :)
Very good bot! It would be nice if the bot opened a thread automatically when a form is posted!
It can be an interesting feature !

**Comment by selenated** [comment]
Do you mean opening a thread with `ff!post` or when a response is received? I'm assuming the former, just asking to clarify as I've seen some people mix terms up 😅

Either way, definitely doable!

**Comment by Allread** [comment]
Indeed :')

I mean when a response is posted 
See screenshot : 

![image](https://user-images.githubusercontent.com/16807391/154695536-c717bd43-0e47-4bf3-b8fa-38070456b8af.png)

**Comment by selenated** [comment]
Added in b574fe7
