### ISSUE TITLE
add help when form is created

### ISSUE THREAD

**Issue by Allread** [greys-bots/form-fox#25]
Hi :) 

i'm new in Form Fox :) Small improvement for new users

Here : 
![image](https://user-images.githubusercontent.com/16807391/154695918-a9fbe97e-4a68-4e19-928d-519e06eed974.png)

Add for help :  
Use ff!post 1c7c #channel for post your form

**Comment by Allread** [comment]
#26

**Comment by selenated** [comment]
Closed with PR mentioned above
