### ISSUE TITLE
[Feature] Slash commands with attributes

### ISSUE THREAD

**Issue by umitseyhan75** [greys-bots/form-fox#44]
Hi, I know this is already in use but I think it needs enhancement. Let me explain it. `/form create` command has two attributes that are being `name` and `description`. But on the other hand why `/form create` command even exist? How about making it this way: `/form` then picking an attribute like `create`. When we enter this command, let an ephemeral message welcome us for the creation process, like defining the `name`, `description`, `questions`etc. The bot in it's current state has **too much** commands which overwhelms.

**Comment by selenated** [comment]
A menu for form creation is already in the works- it's planned as part of the update that'll also bring sections to forms. That said, just having a `/form` command wouldn't work as there are several commands already nested under `/form`, primarily for editing purposes

Changing the command to just be `/form` and then choosing what to do from there might make things less overwhelming, but it would also make things *much* more confusing. Being able to readily see what commands are available without needing a menu to do various actions is the entire point of slash commands, and it keeps things more organized and gives users an idea of what actions can be done with the bot. We'd have a lot of very confused users if we tried to make a change like that 😅

**Comment by umitseyhan75** [comment]
Well, it is your software in the end, what can I say. However I am still behind of my words.
