### ISSUE TITLE
[Feature] Role enhancements

### ISSUE THREAD

**Issue by selenated** [greys-bots/form-fox#8]
Enhancements for adding roles using form-related triggers

- [x] Add roles based on multiple choice/checkbox answers
- [x] Add roles based on other answers (text match, number gt/lt/eq, etc)
- [x] Add roles based on form/response events
    - [x] Apply
    - [x] Submit
    - [x] Accept
    - [x] Deny
- [x] Remove roles on specific events

**Comment by greysdawn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Role enhancements](https://trello.com/c/nzv2iP5P/7-role-enhancements)

**Comment by selenated** [comment]
Finally completed everything here 🥳 Time to close this out!
